# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Project/repository/fpga-based-sdr/FPGA/project_1/project_1.srcs/sources_1/ip/sync_fifo_18bits/sync_fifo_18bits.xci
# IP: The module: 'sync_fifo_18bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Project/repository/fpga-based-sdr/FPGA/project_1/project_1.gen/sources_1/ip/sync_fifo_18bits/sync_fifo_18bits.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_18bits'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Project/repository/fpga-based-sdr/FPGA/project_1/project_1.gen/sources_1/ip/sync_fifo_18bits/sync_fifo_18bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_18bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/Project/repository/fpga-based-sdr/FPGA/project_1/project_1.srcs/sources_1/ip/sync_fifo_18bits/sync_fifo_18bits.xci
# IP: The module: 'sync_fifo_18bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Project/repository/fpga-based-sdr/FPGA/project_1/project_1.gen/sources_1/ip/sync_fifo_18bits/sync_fifo_18bits.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_18bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Project/repository/fpga-based-sdr/FPGA/project_1/project_1.gen/sources_1/ip/sync_fifo_18bits/sync_fifo_18bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_18bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
