set_property PACKAGE_PIN R4 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN AB5 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN AB1 [get_ports o_led_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_led_0]
set_property PACKAGE_PIN AB2 [get_ports o_led_1]
set_property IOSTANDARD LVCMOS33 [get_ports o_led_1]
set_property PACKAGE_PIN AB3 [get_ports o_led_2]
set_property IOSTANDARD LVCMOS33 [get_ports o_led_2]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 6 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]


set_property PACKAGE_PIN E3 [get_ports {FT601_BE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_BE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_BE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_BE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_BE[0]}]
set_property PACKAGE_PIN F3 [get_ports {FT601_BE[2]}]
set_property PACKAGE_PIN G3 [get_ports {FT601_BE[1]}]
set_property PACKAGE_PIN H3 [get_ports {FT601_BE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FT601_DATA[0]}]
set_property PACKAGE_PIN T3 [get_ports {FT601_DATA[7]}]
set_property PACKAGE_PIN T1 [get_ports {FT601_DATA[6]}]
set_property PACKAGE_PIN U2 [get_ports {FT601_DATA[5]}]
set_property PACKAGE_PIN U1 [get_ports {FT601_DATA[4]}]
set_property PACKAGE_PIN V2 [get_ports {FT601_DATA[3]}]
set_property PACKAGE_PIN W2 [get_ports {FT601_DATA[2]}]
set_property PACKAGE_PIN W1 [get_ports {FT601_DATA[1]}]
set_property PACKAGE_PIN Y2 [get_ports {FT601_DATA[0]}]
set_property PACKAGE_PIN R1 [get_ports {FT601_DATA[8]}]
set_property PACKAGE_PIN R2 [get_ports {FT601_DATA[9]}]
set_property PACKAGE_PIN P1 [get_ports {FT601_DATA[10]}]
set_property PACKAGE_PIN P2 [get_ports {FT601_DATA[11]}]
set_property PACKAGE_PIN N2 [get_ports {FT601_DATA[12]}]
set_property PACKAGE_PIN M1 [get_ports {FT601_DATA[13]}]
set_property PACKAGE_PIN M2 [get_ports {FT601_DATA[14]}]
set_property PACKAGE_PIN L1 [get_ports {FT601_DATA[15]}]
set_property PACKAGE_PIN K1 [get_ports {FT601_DATA[16]}]
set_property PACKAGE_PIN K6 [get_ports {FT601_DATA[17]}]
set_property PACKAGE_PIN J1 [get_ports {FT601_DATA[18]}]
set_property PACKAGE_PIN J6 [get_ports {FT601_DATA[19]}]
set_property PACKAGE_PIN H5 [get_ports {FT601_DATA[20]}]
set_property PACKAGE_PIN G1 [get_ports {FT601_DATA[21]}]
set_property PACKAGE_PIN G4 [get_ports {FT601_DATA[22]}]
set_property PACKAGE_PIN F4 [get_ports {FT601_DATA[23]}]
set_property PACKAGE_PIN E1 [get_ports {FT601_DATA[24]}]
set_property PACKAGE_PIN E2 [get_ports {FT601_DATA[25]}]
set_property PACKAGE_PIN D1 [get_ports {FT601_DATA[26]}]
set_property PACKAGE_PIN D2 [get_ports {FT601_DATA[27]}]
set_property PACKAGE_PIN C2 [get_ports {FT601_DATA[28]}]
set_property PACKAGE_PIN B1 [get_ports {FT601_DATA[29]}]
set_property PACKAGE_PIN B2 [get_ports {FT601_DATA[30]}]
set_property PACKAGE_PIN A1 [get_ports {FT601_DATA[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports FT601_clk]
set_property IOSTANDARD LVCMOS33 [get_ports FT601_OE_N]
set_property IOSTANDARD LVCMOS33 [get_ports FT601_RD_N]
set_property IOSTANDARD LVCMOS33 [get_ports FT601_RXF_N]
set_property IOSTANDARD LVCMOS33 [get_ports FT601_SIWU_N]
set_property IOSTANDARD LVCMOS33 [get_ports FT601_TXE_N]
set_property IOSTANDARD LVCMOS33 [get_ports FT601_WR_N]
set_property PACKAGE_PIN K4 [get_ports FT601_clk]
set_property PACKAGE_PIN K2 [get_ports FT601_OE_N]
set_property PACKAGE_PIN K3 [get_ports FT601_RD_N]
set_property PACKAGE_PIN J4 [get_ports FT601_RXF_N]
set_property PACKAGE_PIN H2 [get_ports FT601_SIWU_N]
set_property PACKAGE_PIN G2 [get_ports FT601_TXE_N]
set_property PACKAGE_PIN J2 [get_ports FT601_WR_N]
